### ISSUE TITLE
Beckhoff.TwinCAT.EventLoggerExcelAddin download?

### ISSUE THREAD

**Issue by runtimevic** [Beckhoff-USA-Community/PackML_PLC_Example#1]
Hello , 
where can I get or download Beckhoff.TwinCAT.EventLoggerExcelAddin?
thanks you, Víctor.

**Comment by MarkLewis-Beckhoff** [comment]
Local TwinCAT / Automation Product team should be able to help with that.

**Comment by runtimevic** [comment]
> Local TwinCAT / Automation Product team should be able to help with that.

Hello, 
please send Beckhoff.TwinCAT.EventLoggerExcelAddin ...
my email: victorduranm@hotmail.com
best regards, Víctor.

**Comment by MarkLewis-Beckhoff** [comment]
local teams to handle
