### ISSUE TITLE
Text version of VFFS_Demo.PDF - TwinCAT with TR88.00.02 Methodology

### ISSUE THREAD

**Issue by damianjurkiewicz** [Beckhoff-USA-Community/PackML_PLC_Example#9]
Hello,
Could you provide a version of VFFS_Demo.pdf that is saved as a document with text? The current version is saved as an image, so it's not possible to search for text, navigate, etc.

**Comment by KeithBaker123** [comment]
Original Word Document was saved as a PDF from word and not printed to PDF.

**Comment by KeithBaker123** [comment]
New PDF that is text searchable and linked TOC

**Comment by damianjurkiewicz** [comment]
Thank you
